package edu.sjsu.cmpe275.entities;

// Generated Nov 22, 2015 8:22:29 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SharedProjects generated by hbm2java
 */
@Entity
@Table(name = "SHARED_PROJECTS", catalog = "CMPE275_PROJECT_MGMT_DB")
public class SharedProjects implements java.io.Serializable {

	private int sharedPrjctId;
	private int sharedPrsnId;
	private char acceptedFlag;

	public SharedProjects() {
	}

	public SharedProjects(int sharedPrjctId, int sharedPrsnId) {
		this.sharedPrjctId = sharedPrjctId;
		this.sharedPrsnId = sharedPrsnId;
	}

	@Column(name = "SHARED_PRJCT_ID", nullable = false)
	public int getSharedPrjctId() {
		return this.sharedPrjctId;
	}

	public void setSharedPrjctId(int sharedPrjctId) {
		this.sharedPrjctId = sharedPrjctId;
	}

	@Column(name = "SHARED_PRSN_ID", nullable = false)
	public int getSharedPrsnId() {
		return this.sharedPrsnId;
	}

	public void setSharedPrsnId(int sharedPrsnId) {
		this.sharedPrsnId = sharedPrsnId;
	}

	@Column(name = "ACCEPTED_FLAG", nullable = false, length = 1)
	public char getAcceptedFlag() {
		return this.acceptedFlag;
	}

	public void setAcceptedFlag(char acceptedFlag) {
		this.acceptedFlag = acceptedFlag;
	}

}
